"""Generate a self-contained HTML evaluation report from results JSON."""

from __future__ import annotations

import json
import sys
from html import escape
from pathlib import Path


LOCALES = {
    "en": {
        "title": "Agent Evaluator Report",
        "source": "Source",
        "total_tasks": "Total Tasks",
        "passed": "Passed",
        "failed": "Failed",
        "avg_score": "Average Score",
        "eval_breakdown": "Evaluator Breakdown",
        "difficulty": "Difficulty",
        "tasks": "Tasks",
        "task_results": "Task Results",
        "conversation": "Conversation Trajectory",
        "steps": "steps",
        "analysis": "Failure Analysis",
        "footer": "Generated by Agent Evaluator",
        "pass": "PASS",
        "fail": "FAIL",
        "consistency": "Consistency Metrics",
        "saturation": "Saturation Warning",
        "pass_rate": "Pass Rate",
    },
    "zh": {
        "title": "Agent 评估报告",
        "source": "数据来源",
        "total_tasks": "总任务数",
        "passed": "通过",
        "failed": "失败",
        "avg_score": "平均得分",
        "eval_breakdown": "评估器分项",
        "difficulty": "难度",
        "tasks": "任务数",
        "task_results": "任务详情",
        "conversation": "对话轨迹",
        "steps": "步",
        "analysis": "失败分析",
        "footer": "由 Agent Evaluator 生成",
        "pass": "通过",
        "fail": "失败",
        "consistency": "一致性指标",
        "saturation": "饱和度警告",
        "pass_rate": "通过率",
    },
}


def load_results(path: str) -> list[dict]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_html(results: list[dict], source_path: str, lang: str = "en", analysis: str = "") -> str:
    t = LOCALES.get(lang, LOCALES["en"])

    # Extract metadata from results if embedded, and filter it out
    trial_stats = {}
    saturation_warning = ""
    if not analysis:
        for r in results:
            if "_analysis" in r:
                analysis = r["_analysis"]
            if "_trial_stats" in r:
                trial_stats = r["_trial_stats"]
            if "_saturation_warning" in r:
                saturation_warning = r["_saturation_warning"]
    results = [r for r in results if not any(k.startswith("_") for k in r)]

    total = len(results)
    passed = sum(1 for r in results if r.get("overall_score", 0) >= 1.0 - 1e-6)
    failed = total - passed
    avg_score = sum(r.get("overall_score", 0) for r in results) / total if total else 0

    # Collect evaluator names
    eval_names = set()
    for r in results:
        eval_names.update(r.get("scores", {}).keys())
    eval_names = sorted(eval_names)

    # Per-evaluator averages
    eval_avgs = {}
    for name in eval_names:
        scores = [r.get("scores", {}).get(name, 0) for r in results]
        eval_avgs[name] = sum(scores) / len(scores) if scores else 0

    # Difficulty breakdown
    by_diff: dict[str, list[dict]] = {}
    for r in results:
        diff = r.get("task", {}).get("difficulty", "unknown")
        by_diff.setdefault(diff, []).append(r)

    # Build task cards
    task_cards = "\n".join(_render_task_card(r, eval_names, t) for r in results)

    # Build evaluator chart bars
    eval_bars = "\n".join(
        f'<div class="eval-bar-row">'
        f'<span class="eval-bar-label">{escape(name)}</span>'
        f'<div class="eval-bar-track"><div class="eval-bar-fill" style="width:{avg*100:.1f}%">'
        f'{avg:.0%}</div></div></div>'
        for name, avg in eval_avgs.items()
    )

    # Difficulty breakdown rows
    diff_rows = "\n".join(
        f'<tr><td>{escape(diff)}</td>'
        f'<td>{len(rs)}</td>'
        f'<td>{sum(r.get("overall_score",0) for r in rs)/len(rs):.0%}</td></tr>'
        for diff, rs in sorted(by_diff.items())
    )

    # Build capability radar chart SVG
    radar_html = _render_radar_chart(eval_avgs, avg_score, t)

    # Build analysis section
    analysis_html = ""
    if analysis:
        analysis_html = (
            f'<div class="analysis-section">'
            f'<h2>{t["analysis"]}</h2>'
            f'<div class="analysis-content">{escape(analysis)}</div>'
            f'</div>'
        )

    # Build saturation warning HTML
    saturation_html = ""
    if saturation_warning:
        saturation_html = (
            f'<div class="analysis-section" style="border-left-color:var(--yellow)">'
            f'<h2>{t["saturation"]}</h2>'
            f'<div class="analysis-content">{escape(saturation_warning)}</div>'
            f'</div>'
        )

    # Build trial stats HTML
    consistency_html = ""
    if trial_stats:
        rows = ""
        for tid, st in trial_stats.items():
            k_cols = ""
            for key, val in st.items():
                if key in ("n", "c"):
                    continue
                if isinstance(val, float):
                    k_cols += f"<td>{val:.2f}</td>"
                else:
                    k_cols += f"<td>{val}</td>"
            rows += f"<tr><td>{escape(tid)}</td>{k_cols}</tr>\n"
        # Build header from first entry's keys
        first_st = next(iter(trial_stats.values()))
        headers = "".join(
            f"<th>{k}</th>" for k in first_st if k not in ("n", "c")
        )
        consistency_html = (
            f'<div class="eval-section">'
            f'<h2>{t["consistency"]}</h2>'
            f'<table class="diff-table"><tr><th>Task</th>{headers}</tr>'
            f'{rows}</table></div>'
        )

    return HTML_TEMPLATE.format(
        lang=lang,
        title=t["title"],
        source_label=t["source"],
        source=escape(source_path),
        total=total,
        passed=passed,
        failed=failed,
        avg_score=f"{avg_score:.0%}",
        label_total=t["total_tasks"],
        label_passed=t["passed"],
        label_failed=t["failed"],
        label_avg=t["avg_score"],
        label_eval=t["eval_breakdown"],
        label_diff=t["difficulty"],
        label_tasks=t["tasks"],
        label_avg_score=t["avg_score"],
        label_results=t["task_results"],
        footer=t["footer"],
        eval_bars=eval_bars,
        diff_rows=diff_rows,
        task_cards=task_cards,
        analysis_section=analysis_html,
        saturation_section=saturation_html,
        consistency_section=consistency_html,
        radar_section=radar_html,
    )


DIMENSION_LABELS = {
    "en": {
        "state_match": "Task Completion",
        "action_match": "Tool Usage",
        "info_delivery": "Communication",
        "llm_judge": "Response Quality",
        "nl_assertion": "Reasoning",
    },
    "zh": {
        "state_match": "任务完成",
        "action_match": "工具使用",
        "info_delivery": "信息传达",
        "llm_judge": "回复质量",
        "nl_assertion": "推理能力",
    },
}


def _render_radar_chart(eval_avgs: dict[str, float], overall: float, t: dict) -> str:
    """Generate an SVG radar chart for capability dimensions."""
    import math

    if not eval_avgs or len(eval_avgs) < 3:
        return ""

    lang = "zh" if "评估" in t.get("title", "") else "en"
    labels_map = DIMENSION_LABELS.get(lang, DIMENSION_LABELS["en"])

    dimensions = list(eval_avgs.keys())
    values = [eval_avgs[d] for d in dimensions]
    labels = [labels_map.get(d, d) for d in dimensions]
    n = len(dimensions)

    cx, cy, r = 150, 150, 120
    angle_offset = -math.pi / 2  # start from top

    def polar(i, scale=1.0):
        angle = angle_offset + 2 * math.pi * i / n
        x = cx + r * scale * math.cos(angle)
        y = cy + r * scale * math.sin(angle)
        return x, y

    # Grid rings
    grid_svg = ""
    for level in [0.25, 0.5, 0.75, 1.0]:
        points = " ".join(f"{polar(i, level)[0]:.1f},{polar(i, level)[1]:.1f}" for i in range(n))
        grid_svg += f'<polygon points="{points}" fill="none" stroke="var(--border)" stroke-width="0.5"/>\n'

    # Axis lines
    axes_svg = ""
    for i in range(n):
        x, y = polar(i, 1.0)
        axes_svg += f'<line x1="{cx}" y1="{cy}" x2="{x:.1f}" y2="{y:.1f}" stroke="var(--border)" stroke-width="0.5"/>\n'

    # Data polygon
    data_points = " ".join(f"{polar(i, values[i])[0]:.1f},{polar(i, values[i])[1]:.1f}" for i in range(n))
    data_svg = f'<polygon points="{data_points}" fill="rgba(31,111,235,0.25)" stroke="var(--accent)" stroke-width="2"/>\n'

    # Data dots
    dots_svg = ""
    for i in range(n):
        x, y = polar(i, values[i])
        dots_svg += f'<circle cx="{x:.1f}" cy="{y:.1f}" r="3" fill="var(--accent)"/>\n'

    # Labels
    label_svg = ""
    for i in range(n):
        x, y = polar(i, 1.18)
        anchor = "middle"
        if x < cx - 10:
            anchor = "end"
        elif x > cx + 10:
            anchor = "start"
        label_svg += (
            f'<text x="{x:.1f}" y="{y:.1f}" text-anchor="{anchor}" '
            f'fill="var(--text2)" font-size="11">{escape(labels[i])} ({values[i]:.0%})</text>\n'
        )

    radar_title = {"en": "Capability Radar", "zh": "能力雷达图"}.get(lang, "Capability Radar")

    return (
        f'<div class="eval-section">'
        f'<h2>{radar_title}</h2>'
        f'<div style="text-align:center">'
        f'<svg viewBox="0 0 300 300" width="340" height="340" style="max-width:100%">'
        f'{grid_svg}{axes_svg}{data_svg}{dots_svg}{label_svg}'
        f'</svg></div></div>'
    )


def _render_task_card(result: dict, eval_names: list[str], t: dict) -> str:
    task_id = result.get("task_id", "unknown")
    task_info = result.get("task", {})
    desc = task_info.get("description", "")
    difficulty = task_info.get("difficulty", "")
    overall = result.get("overall_score", 0)
    terminated = result.get("terminated", "")
    steps = result.get("steps_taken", 0)
    elapsed = result.get("elapsed_seconds", 0)
    is_pass = overall >= 1.0 - 1e-6

    # Score bars
    score_bars = ""
    for name in eval_names:
        score = result.get("scores", {}).get(name, 0)
        score_bars += (
            f'<div class="score-row">'
            f'<span class="score-label">{escape(name)}</span>'
            f'<div class="score-track"><div class="score-fill {_score_color(score)}" '
            f'style="width:{score*100:.1f}%"></div></div>'
            f'<span class="score-value">{score:.2f}</span></div>\n'
        )

    # Trajectory
    traj_html = _render_trajectory(result.get("trajectory", []))

    status_class = "pass" if is_pass else "fail"
    status_text = t["pass"] if is_pass else t["fail"]

    return f"""
    <div class="task-card {status_class}">
      <div class="task-header">
        <span class="task-status {status_class}">{status_text}</span>
        <span class="task-id">{escape(task_id)}</span>
        <span class="task-diff">{escape(difficulty)}</span>
        <span class="task-meta">{steps} {t['steps']} &middot; {elapsed:.1f}s &middot; {escape(terminated)}</span>
        <span class="task-overall">{overall:.2f}</span>
      </div>
      <p class="task-desc">{escape(desc)}</p>
      <div class="scores-section">{score_bars}</div>
      <details class="trajectory-details">
        <summary>{t['conversation']}</summary>
        <div class="trajectory">{traj_html}</div>
      </details>
    </div>"""


_MSG_COLLAPSE_THRESHOLD = 300  # chars before collapsing


def _render_long_content(content: str, role_class: str, role_label: str, use_code: bool = False) -> str:
    """Render message content, collapsible if long, with copy button."""
    escaped = escape(content)
    length = len(content)

    if length <= _MSG_COLLAPSE_THRESHOLD:
        tag = "code" if use_code else "span"
        return (
            f'<div class="msg {role_class}"><span class="role">{role_label}</span>'
            f'<{tag}>{escaped}</{tag}></div>\n'
        )

    # Long content: show preview + expandable full content
    preview = escape(content[:200] + "...")
    msg_id = f"msg-{id(content) % 100000}"
    tag = "code" if use_code else "span"
    return (
        f'<div class="msg {role_class}">'
        f'<span class="role">{role_label}</span>'
        f'<span class="msg-meta">{length} chars</span>'
        f'<button class="copy-btn" onclick="navigator.clipboard.writeText('
        f'document.getElementById(\'{msg_id}-full\').textContent)">Copy</button>'
        f'<{tag} class="msg-preview" id="{msg_id}-preview">{preview}</{tag}>'
        f'<{tag} class="msg-full" id="{msg_id}-full" style="display:none">{escaped}</{tag}>'
        f'<button class="expand-btn" onclick="toggleMsg(\'{msg_id}\')">Expand</button>'
        f'</div>\n'
    )


def _render_trajectory(trajectory: list[dict]) -> str:
    html = ""
    for msg in trajectory:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        if not isinstance(content, str):
            content = json.dumps(content, ensure_ascii=False, indent=2) if content else ""
        tool_calls = msg.get("tool_calls", [])
        tool_results = msg.get("tool_results", [])

        if role == "system":
            html += _render_long_content(content, "msg-system", "SYSTEM")
        elif role == "user":
            html += _render_long_content(content or "", "msg-user", "USER")
        elif role == "agent":
            if content:
                html += _render_long_content(content, "msg-agent", "AGENT")
            for tc in tool_calls:
                args = json.dumps(tc.get("arguments", {}), ensure_ascii=False, indent=2)
                call_text = f'{tc.get("name", "")}({args})'
                html += _render_long_content(call_text, "msg-tool-call", "TOOL CALL", use_code=True)
        elif role == "env":
            for tr in tool_results:
                output = tr.get("output", "")
                is_err = tr.get("error", False)
                cls = "msg-env-error" if is_err else "msg-env"
                html += _render_long_content(output, cls, "ENV", use_code=True)
    return html


def _score_color(score: float) -> str:
    if score >= 0.9:
        return "green"
    elif score >= 0.5:
        return "yellow"
    return "red"


HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
:root {{
  --bg: #0d1117; --surface: #161b22; --border: #30363d;
  --text: #e6edf3; --text2: #8b949e; --green: #3fb950;
  --red: #f85149; --yellow: #d29922; --blue: #58a6ff;
  --accent: #1f6feb;
}}
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
  background: var(--bg); color: var(--text); padding: 24px; line-height: 1.5; }}
h1 {{ font-size: 1.5rem; margin-bottom: 4px; }}
.source {{ color: var(--text2); font-size: 0.85rem; margin-bottom: 24px; }}

/* Dashboard */
.dashboard {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 16px; margin-bottom: 32px; }}
.stat-card {{ background: var(--surface); border: 1px solid var(--border);
  border-radius: 8px; padding: 16px; text-align: center; }}
.stat-value {{ font-size: 2rem; font-weight: 700; }}
.stat-value.green {{ color: var(--green); }}
.stat-value.red {{ color: var(--red); }}
.stat-value.blue {{ color: var(--blue); }}
.stat-label {{ color: var(--text2); font-size: 0.85rem; }}

/* Evaluator bars */
.eval-section {{ background: var(--surface); border: 1px solid var(--border);
  border-radius: 8px; padding: 20px; margin-bottom: 32px; }}
.eval-section h2 {{ font-size: 1.1rem; margin-bottom: 12px; }}
.eval-bar-row {{ display: flex; align-items: center; margin-bottom: 8px; }}
.eval-bar-label {{ width: 140px; font-size: 0.85rem; color: var(--text2); }}
.eval-bar-track {{ flex: 1; height: 24px; background: var(--border); border-radius: 4px; overflow: hidden; }}
.eval-bar-fill {{ height: 100%; background: var(--accent); border-radius: 4px;
  display: flex; align-items: center; justify-content: flex-end; padding-right: 8px;
  font-size: 0.8rem; font-weight: 600; min-width: 40px; }}
.diff-table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
.diff-table th, .diff-table td {{ padding: 6px 12px; text-align: left;
  border-bottom: 1px solid var(--border); font-size: 0.9rem; }}
.diff-table th {{ color: var(--text2); }}

/* Task cards */
.task-card {{ background: var(--surface); border: 1px solid var(--border);
  border-radius: 8px; padding: 16px; margin-bottom: 16px; }}
.task-card.pass {{ border-left: 3px solid var(--green); }}
.task-card.fail {{ border-left: 3px solid var(--red); }}
.task-header {{ display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-bottom: 8px; }}
.task-status {{ font-weight: 700; font-size: 0.8rem; padding: 2px 8px; border-radius: 4px; }}
.task-status.pass {{ background: rgba(63,185,80,0.15); color: var(--green); }}
.task-status.fail {{ background: rgba(248,81,73,0.15); color: var(--red); }}
.task-id {{ font-weight: 600; }}
.task-diff {{ background: var(--border); padding: 2px 8px; border-radius: 4px; font-size: 0.8rem; }}
.task-meta {{ color: var(--text2); font-size: 0.85rem; margin-left: auto; }}
.task-overall {{ font-weight: 700; font-size: 1.1rem; }}
.task-desc {{ color: var(--text2); font-size: 0.9rem; margin-bottom: 12px; }}

/* Score bars */
.score-row {{ display: flex; align-items: center; margin-bottom: 4px; }}
.score-label {{ width: 120px; font-size: 0.8rem; color: var(--text2); }}
.score-track {{ flex: 1; height: 16px; background: var(--border); border-radius: 3px; overflow: hidden; }}
.score-fill {{ height: 100%; border-radius: 3px; transition: width 0.3s; }}
.score-fill.green {{ background: var(--green); }}
.score-fill.yellow {{ background: var(--yellow); }}
.score-fill.red {{ background: var(--red); }}
.score-value {{ width: 40px; text-align: right; font-size: 0.8rem; font-weight: 600; }}

/* Trajectory */
.trajectory-details {{ margin-top: 12px; }}
.trajectory-details summary {{ cursor: pointer; color: var(--blue); font-size: 0.9rem; }}
.trajectory {{ margin-top: 8px; max-height: none; overflow-y: visible;
  border: 1px solid var(--border); border-radius: 6px; padding: 12px; }}
.msg {{ padding: 8px 12px; margin-bottom: 6px; border-radius: 6px; font-size: 0.85rem;
  white-space: pre-wrap; word-break: break-word; position: relative; }}
.msg-meta {{ font-size: 0.7rem; color: var(--text2); margin-left: 8px; }}
.msg-full {{ display: none; }}
.expand-btn, .copy-btn {{ background: var(--border); color: var(--text2); border: none;
  border-radius: 3px; padding: 2px 8px; font-size: 0.7rem; cursor: pointer;
  margin-left: 6px; vertical-align: middle; }}
.expand-btn:hover, .copy-btn:hover {{ background: var(--accent); color: var(--text); }}
.role {{ display: inline-block; font-weight: 700; font-size: 0.75rem; margin-right: 8px;
  padding: 1px 6px; border-radius: 3px; }}
.msg-system {{ background: rgba(88,166,255,0.08); }}
.msg-system .role {{ background: rgba(88,166,255,0.2); color: var(--blue); }}
.msg-user {{ background: rgba(63,185,80,0.08); }}
.msg-user .role {{ background: rgba(63,185,80,0.2); color: var(--green); }}
.msg-agent {{ background: rgba(210,153,34,0.08); }}
.msg-agent .role {{ background: rgba(210,153,34,0.2); color: var(--yellow); }}
.msg-tool-call {{ background: rgba(139,148,158,0.08); }}
.msg-tool-call .role {{ background: rgba(139,148,158,0.2); color: var(--text2); }}
.msg-tool-call code {{ font-size: 0.82rem; }}
.msg-env {{ background: rgba(139,148,158,0.05); }}
.msg-env .role {{ background: rgba(139,148,158,0.15); color: var(--text2); }}
.msg-env code {{ font-size: 0.82rem; }}
.msg-env-error {{ background: rgba(248,81,73,0.08); }}
.msg-env-error .role {{ background: rgba(248,81,73,0.2); color: var(--red); }}

/* Analysis section */
.analysis-section {{ background: var(--surface); border: 1px solid var(--border);
  border-left: 3px solid var(--yellow); border-radius: 8px; padding: 20px; margin-bottom: 32px; }}
.analysis-section h2 {{ font-size: 1.1rem; margin-bottom: 12px; color: var(--yellow); }}
.analysis-content {{ font-size: 0.9rem; line-height: 1.8; white-space: pre-wrap; color: var(--text); }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="source">{source_label}: {source}</p>

<div class="dashboard">
  <div class="stat-card">
    <div class="stat-value blue">{total}</div>
    <div class="stat-label">{label_total}</div>
  </div>
  <div class="stat-card">
    <div class="stat-value green">{passed}</div>
    <div class="stat-label">{label_passed}</div>
  </div>
  <div class="stat-card">
    <div class="stat-value red">{failed}</div>
    <div class="stat-label">{label_failed}</div>
  </div>
  <div class="stat-card">
    <div class="stat-value blue">{avg_score}</div>
    <div class="stat-label">{label_avg}</div>
  </div>
</div>

<div class="eval-section">
  <h2>{label_eval}</h2>
  {eval_bars}
  <table class="diff-table">
    <tr><th>{label_diff}</th><th>{label_tasks}</th><th>{label_avg_score}</th></tr>
    {diff_rows}
  </table>
</div>

{radar_section}

{saturation_section}

{consistency_section}

{analysis_section}

<h2 style="margin-bottom:12px">{label_results}</h2>
{task_cards}

<p style="color:var(--text2);font-size:0.8rem;margin-top:24px;text-align:center">
  {footer}
</p>
<script>
function toggleMsg(id) {{
  var preview = document.getElementById(id + '-preview');
  var full = document.getElementById(id + '-full');
  var btn = event.target;
  if (full.style.display === 'none') {{
    full.style.display = 'inline';
    preview.style.display = 'none';
    btn.textContent = 'Collapse';
  }} else {{
    full.style.display = 'none';
    preview.style.display = 'inline';
    btn.textContent = 'Expand';
  }}
}}
</script>
</body>
</html>"""


def main():
    if len(sys.argv) < 2:
        print("Usage: python report.py <results.json> [output.html] [--lang en|zh]")
        sys.exit(1)

    results_path = sys.argv[1]

    # Parse --lang flag
    lang = "en"
    args = sys.argv[2:]
    positional = []
    i = 0
    while i < len(args):
        if args[i] == "--lang" and i + 1 < len(args):
            lang = args[i + 1]
            i += 2
        else:
            positional.append(args[i])
            i += 1

    output_path = positional[0] if positional else results_path.replace(".json", f"_{lang}.html")

    results = load_results(results_path)
    html = generate_html(results, results_path, lang=lang)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"Report generated: {output_path}")


if __name__ == "__main__":
    main()
